# Generated by Django 6.0.3 on 2026-05-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_ordemservicos'),
        ('servicos', '0002_produtosservico_servico_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(through='agendamentos.OrdemServicos', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
